version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install --upgrade pip
      - pip install --group docs
      - pip install .

sphinx:
  configuration: docs/conf.py
