[tox]
env_list =
    start_containers
    coverage-erase

    # IF YOU NEED TO EDIT THIS LINE, USE SEARCH-AND-REPLACE!
    # Changes MUST be replicated to all locations in this file.
    {py3.10, py3.11, py3.12, py3.13, py3.14, pypy3.10, pypy3.11}-{standalone, cluster}-resp{2, 3}-{plain, libvalkey}

    coverage-combine
    coverage-html
    stop_containers

    # IF YOU NEED TO EDIT THIS LINE, USE SEARCH-AND-REPLACE!
    # Changes MUST be replicated to all locations in this file.
    mypy-py{3.10, 3.11, 3.12, 3.13, 3.14}

    docs
    build{, -minimum}

[testenv]
package = wheel
wheel_build_env = build_wheel


[testenv:start_containers]
description = Start the Docker containers
skip_install = true
allowlist_externals =
    bash
    docker
pass_env =
    VALKEY_DOCKER_TAG
commands =
    docker compose --profile all up --wait


[testenv:{py3.10, py3.11, py3.12, py3.13, py3.14, pypy3.10, pypy3.11}-{standalone, cluster}-resp{2, 3}-{plain, libvalkey}]
description = Test the code on Python {py_dot_ver}
dependency_groups =
    dev
extras =
    libvalkey: libvalkey
depends =
    start_containers
    coverage-erase
set_env =
    # `--protocol` equivalents
    resp2:      TARGET_RESP_PROTOCOL=2
    resp3:      TARGET_RESP_PROTOCOL=3
    # `--valkey-url` equivalents
    standalone: TARGET_VALKEY_URL=valkey://localhost:6379/0
    cluster:    TARGET_VALKEY_URL=valkey://localhost:16379/0
commands =
    standalone: coverage run -m pytest -v -m 'not onlycluster' -W all {posargs}
    cluster:    coverage run -m pytest -v -m 'not onlynoncluster and not valkeymod' -W all {posargs}


[testenv:stop_containers]
description = Stop the Docker containers
skip_install = true
allowlist_externals =
    docker
commands =
    docker compose --profile all down
depends =
    {py3.10, py3.11, py3.12, py3.13, py3.14, pypy3.10, pypy3.11}-{standalone, cluster}-resp{2, 3}-{plain, libvalkey}


[testenv:coverage_base]
description = Base config for coverage-* environments
deps =
    coverage

[testenv:coverage-erase]
description = Erase coverage data files
base = coverage_base
commands =
    - coverage erase

[testenv:coverage-combine]
description = Combine all coverage files
base = coverage_base
depends =
    {py3.10, py3.11, py3.12, py3.13, py3.14, pypy3.10, pypy3.11}-{standalone, cluster}-resp{2, 3}-{plain, libvalkey}
commands =
    - coverage combine

[testenv:coverage-html]
description = Create an HTML coverage report
base = coverage_base
depends =
    coverage-combine
commands =
    coverage html

[testenv:mypy-py{3.10, 3.11, 3.12, 3.13, 3.14}]
description = Test type annotations on Python {py_dot_ver}
skip_install = true
deps =
    mypy
    types-requests
    cryptography
    libvalkey
commands =
    mypy

[testenv:docs]
description = Test building the documentation
base_python = py3.13
skip_install = true
dependency_groups =
    docs
commands =
    sphinx-build -b html docs docs/_build/html

[testenv:build{,-minimum}]
description =
    Test building the project
    minimum: (minimum requirements)
base_python =
    minimum: py3.10
skip_install = true
recreate = true
deps =
    build
    twine
    minimum: hatchling==0.8.0
    !minimum: hatchling
commands =
    python -m build --outdir {envdir}/dist/ --no-isolation
    twine check --strict {envdir}/dist/*
