from valkey.client import AbstractValkey
from valkey.typing import EncodableT

class CommandsParser:
    commands: dict[str, str]
    def __init__(self, valkey_connection: AbstractValkey) -> None: ...
    def initialize(self, r: AbstractValkey) -> None: ...
    def get_keys(self, valkey_conn: AbstractValkey, *args: EncodableT) -> list[EncodableT] | None: ...
