class ValkeyError(Exception): ...
class AuthenticationError(ValkeyError): ...
class ConnectionError(ValkeyError): ...
class TimeoutError(ValkeyError): ...
class AuthorizationError(ConnectionError): ...
class BusyLoadingError(ConnectionError): ...
class InvalidResponse(ValkeyError): ...
class ResponseError(ValkeyError): ...
class DataError(ValkeyError): ...
class PubSubError(ValkeyError): ...
class WatchError(ValkeyError): ...
class NoScriptError(ResponseError): ...
class OutOfMemoryError(ResponseError): ...
class ExecAbortError(ResponseError): ...
class ReadOnlyError(ResponseError): ...
class NoPermissionError(ResponseError): ...
class ModuleError(ResponseError): ...
class LockError(ValkeyError, ValueError): ...
class LockNotOwnedError(LockError): ...
class ChildDeadlockedError(Exception): ...
class AuthenticationWrongNumberOfArgsError(ResponseError): ...
class ValkeyClusterException(Exception): ...
class ClusterError(ValkeyError): ...

class ClusterDownError(ClusterError, ResponseError):
    args: tuple[str]
    message: str
    def __init__(self, resp: str) -> None: ...

class AskError(ResponseError):
    args: tuple[str]
    message: str
    slot_id: int
    node_addr: tuple[str, int]
    host: str
    port: int
    def __init__(self, resp: str) -> None: ...

class TryAgainError(ResponseError): ...
class ClusterCrossSlotError(ResponseError): ...
class MovedError(AskError): ...
class MasterDownError(ClusterDownError): ...
class SlotNotCoveredError(ValkeyClusterException): ...
